test:
  single:
    - securities:
        - ticker: TQQQ
          underlying_ticker: ^NDX
          daily_return_multiplier: 3.0
          expense_ratio: 0.0082
          weight: 1.0
        - ticker: QQQ
          underlying_ticker: ^NDX
          daily_return_multiplier: 1.0
          expense_ratio: 0.0018
          weight: 0.0
        # - ticker: MLPX
        #   weight: 0.0305
        # - ticker: FDL
        #   weight: 0.02925
        # - ticker: UTES
        #   weight: 0.04025
        # - ticker: BTC-USD
        #   weight: 0.025
        # - ticker: DBP
        #   weight: 0.025
        # - ticker: GPIQ
        #   weight: 0.025
      strategy:
        name: SimpleMovingAverageRebalance
        target: ^NDX
        length: 190
        minimum_primary_rebalance_days: 2
        primary: TQQQ
        alternate: QQQ
        trace: true
        # name: ScheduledRebalance
        # schedule:
        #   mode: static
        #   format: DAYS
        #   value: 270
      allocation:
        mode: static
        schedule:
          format: DAYS
          value: 7
        initial: 10000
        yearly: 1000
        # weights:
        #   TQQQ: 1.0
        #   QQQ: 0.0
        #   UTES: 0.0
        #   FDL: 0.0
        #   MLPX: 0.0
      dates:
        start: "2001-05-04"
        end: "2026-05-04"
      performance:
        benchmark: ^NDX
        risk_free_ticker: ^IRX
  #     trace: false
  # simulate:
  #   - securities:
  #       - ticker: TQQQ
  #         weight: 1.0
  #       - ticker: QQQ
  #         weight: 0.0
  #     strategy:
  #       name: ScheduledRebalance
  #       schedule:
  #         mode: static
  #         format: DAYS
  #         value: 7
  #     allocation:
  #       mode: dynamic
  #       increment: 4
  #       initial: 10000
  #       yearly: 6000
  #     weights:
  #       mode: static
  #     dates:
  #       start: "2026-01-30"
  #       # end: "2026-01-30"
  #     trace: false
